<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title></title>
	<style>
		
	</style>
	<script type="text/javascript" src="./Include/Script.js"></script>
	<link rel="stylesheet" href="./Style/HamburgerStyle.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
		<div id="menu-bar" onclick="showMenu()">
			<div id="menu">
				<div id="bar1" class="bar"></div>
				<div id="bar2" class="bar"></div>
				<div id="bar3" class="bar"></div>
			</div>
			<ul class="nav" id="nav">
				<li><a href="EmployeeList.aspx">従業員一覧</a></li>
				<li><a href="EmployeeRegister.aspx">従業員登録</a></li>
				<li><a href="UserRegister.aspx">利用者登録</a></li>
				<li><a href="GetLicense.aspx">資格取得</a></li>
			</ul>
		</div>
</body>
</html>